pipeline {
    agent any
    
    tools {nodejs "node"}
    
    stages {
        stage('Cloning Git 1') {
            steps {
                git 'https://github.com/pablosiegers/DOTT/tree/master/cidr_convert_api/node'
            }
        }
        stage('Install Dependencies'){
            steps {
                sh 'npm install'
            }
        }
        stage ('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}
